name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  run-test:
    name: Test using deno
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.44

      - name: Run tests
        run: deno test
